
services:
  mysql:
    image: mysql:8.0
    container_name: inventario-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - inventario_data:/var/lib/mysql

volumes:
  inventario_data:
